# Generated by Django 5.1.5 on 2025-08-01 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('rotation_period', models.CharField(max_length=50)),
                ('orbital_period', models.CharField(max_length=50)),
                ('diameter', models.CharField(max_length=50)),
                ('climate', models.CharField(max_length=255)),
                ('gravity', models.CharField(max_length=255)),
                ('terrain', models.CharField(max_length=255)),
                ('surface_water', models.CharField(max_length=50)),
                ('population', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('average_height', models.CharField(max_length=50)),
                ('skin_colors', models.CharField(max_length=255)),
                ('hair_colors', models.CharField(max_length=255)),
                ('eye_colors', models.CharField(max_length=255)),
                ('average_lifespan', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('planet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species', to='core.planet')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=50)),
                ('mass', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=100)),
                ('skin_color', models.CharField(max_length=100)),
                ('eye_color', models.CharField(max_length=100)),
                ('birth_year', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('planet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='core.planet')),
                ('species', models.ManyToManyField(blank=True, related_name='characters', to='core.species')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('cost_in_credits', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=50)),
                ('max_atmosphering_speed', models.CharField(max_length=50)),
                ('crew', models.CharField(max_length=50)),
                ('passengers', models.CharField(max_length=50)),
                ('cargo_capacity', models.CharField(max_length=50)),
                ('consumables', models.CharField(max_length=100)),
                ('hyperdrive_rating', models.CharField(max_length=50)),
                ('MGLT', models.CharField(max_length=50)),
                ('starship_class', models.CharField(max_length=100)),
                ('pilots', models.ManyToManyField(blank=True, related_name='starships', to='core.character')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('cost_in_credits', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=50)),
                ('max_atmosphering_speed', models.CharField(max_length=50)),
                ('crew', models.CharField(max_length=50)),
                ('passengers', models.CharField(max_length=50)),
                ('cargo_capacity', models.CharField(max_length=50)),
                ('consumables', models.CharField(max_length=100)),
                ('vehicle_class', models.CharField(max_length=100)),
                ('pilots', models.ManyToManyField(blank=True, related_name='vehicles', to='core.character')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('episode_id', models.IntegerField()),
                ('opening_crawl', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('characters', models.ManyToManyField(related_name='films', to='core.character')),
                ('planets', models.ManyToManyField(related_name='films', to='core.planet')),
                ('species', models.ManyToManyField(related_name='films', to='core.species')),
                ('starships', models.ManyToManyField(related_name='films', to='core.starship')),
                ('vehicles', models.ManyToManyField(related_name='films', to='core.vehicle')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
