# Generated by Django 5.1.5 on 2025-08-02 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=50)),
                ('mass', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=100)),
                ('skin_color', models.CharField(max_length=100)),
                ('eye_color', models.CharField(max_length=100)),
                ('birth_year', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('cost_in_credits', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=50)),
                ('max_atmosphering_speed', models.CharField(max_length=50)),
                ('crew', models.CharField(max_length=50)),
                ('passengers', models.CharField(max_length=50)),
                ('cargo_capacity', models.CharField(max_length=50)),
                ('consumables', models.CharField(max_length=100)),
                ('hyperdrive_rating', models.CharField(max_length=50)),
                ('MGLT', models.CharField(max_length=50)),
                ('starship_class', models.CharField(max_length=100)),
                ('pilots', models.ManyToManyField(blank=True, related_name='starships', to='core.character')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('episode_id', models.IntegerField()),
                ('opening_crawl', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('characters', models.ManyToManyField(blank=True, related_name='films', to='core.character')),
                ('starships', models.ManyToManyField(blank=True, related_name='films', to='core.starship')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
