# Generated by Django 5.1.5 on 2025-08-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='films', to='core.character'),
        ),
        migrations.AlterField(
            model_name='film',
            name='planets',
            field=models.ManyToManyField(blank=True, related_name='films', to='core.planet'),
        ),
        migrations.AlterField(
            model_name='film',
            name='species',
            field=models.ManyToManyField(blank=True, related_name='films', to='core.species'),
        ),
        migrations.AlterField(
            model_name='film',
            name='starships',
            field=models.ManyToManyField(blank=True, related_name='films', to='core.starship'),
        ),
        migrations.AlterField(
            model_name='film',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='films', to='core.vehicle'),
        ),
    ]
